# Generated by Django 4.1 on 2022-08-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_remove_friend_profile_friend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='profile',
            field=models.OneToOneField(default='ok', on_delete=django.db.models.deletion.CASCADE, to='chatApp.profile'),
            preserve_default=False,
        ),
    ]
