# Generated by Django 4.1 on 2022-08-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_friend_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='name',
        ),
    ]
